# Generated by Django 4.2.30 on 2026-05-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_social_views_captions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={"ordering": ["home_order", "-created_at"]},
        ),
        migrations.AddField(
            model_name="blogpost",
            name="home_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="show_on_home",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="admin_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="message",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notif_type",
            field=models.CharField(
                choices=[
                    ("comment", "Comment on your asset"),
                    ("reply", "Reply to your comment"),
                    ("follow", "New follower"),
                    ("admin_action", "Admin action"),
                ],
                max_length=20,
            ),
        ),
    ]
