# Generated by Django 4.2.30 on 2026-05-02 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0008_alter_blogpost_options_blogpost_home_order_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrendingOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")], max_length=10
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.generatedimage",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.generatedvideo",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdminActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("asset_deleted", "Asset deleted"),
                            ("asset_unpublished", "Asset unpublished"),
                            ("asset_moderated", "Asset moderated"),
                            ("coins_added", "Coins added"),
                            ("coins_removed", "Coins removed"),
                            ("user_deactivated", "User deactivated"),
                            ("user_reactivated", "User reactivated"),
                            ("staff_granted", "Staff granted"),
                            ("staff_revoked", "Staff revoked"),
                            ("superuser_granted", "Superuser granted"),
                            ("superuser_revoked", "Superuser revoked"),
                            ("coin_request_approved", "Coin request approved"),
                            ("coin_request_rejected", "Coin request rejected"),
                            ("content_updated", "Content updated"),
                        ],
                        max_length=40,
                    ),
                ),
                ("asset_type", models.CharField(blank=True, max_length=10)),
                ("asset_id", models.PositiveIntegerField(blank=True, null=True)),
                ("object_label", models.CharField(blank=True, max_length=220)),
                ("note", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("email_sent", models.BooleanField(default=False)),
                ("email_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_actions_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_actions_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="trendingoverride",
            constraint=models.UniqueConstraint(
                condition=models.Q(("image__isnull", False)),
                fields=("asset_type", "image"),
                name="unique_trending_image_override",
            ),
        ),
        migrations.AddConstraint(
            model_name="trendingoverride",
            constraint=models.UniqueConstraint(
                condition=models.Q(("video__isnull", False)),
                fields=("asset_type", "video"),
                name="unique_trending_video_override",
            ),
        ),
        migrations.AddIndex(
            model_name="adminactionlog",
            index=models.Index(
                fields=["action", "created_at"], name="moderation__action_dec880_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adminactionlog",
            index=models.Index(
                fields=["target_user", "created_at"],
                name="moderation__target__a62ae2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="adminactionlog",
            index=models.Index(
                fields=["asset_type", "asset_id"], name="moderation__asset_t_c093a3_idx"
            ),
        ),
    ]
